src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $category_id = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategoryId(): ?string
    {
        return $this->category_id;
    }

    public function setCategoryId(string $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/BookRead.php
<?php

namespace App\Entity;

use App\Repository\BookReadRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookReadRepository::class)]
class BookRead
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $book_id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2, nullable: true)]
    private ?string $rating = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $is_read = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cover = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getBookId(): ?string
    {
        return $this->book_id;
    }

    public function setBookId(string $book_id): static
    {
        $this->book_id = $book_id;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(?string $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isRead(): ?bool
    {
        return $this->is_read;
    }

    public function setRead(bool $is_read): static
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): static
    {
        $this->cover = $cover;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BookReadRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    private BookReadRepository $readBookRepository;

    // Inject the repository via the constructor
    public function __construct(BookReadRepository $bookReadRepository)
    {
        $this->bookReadRepository = $bookReadRepository;
    }

    #[Route('/', name: 'app.home')]
    public function index(): Response
    {
        $userId     = 1;
        $booksRead  = $this->bookReadRepository->findByUserId($userId, false);

        // Render the 'hello.html.twig' template
        return $this->render('pages/home.html.twig', [
            'booksRead' => $booksRead,
            'name'      => 'Accueil', // Pass data to the view
        ]);
    }


    #[Route('/login', name: 'auth.login')]
    public function login(): Response
    {
        // Render the 'hello.html.twig' template
        return $this->render('auth/login.html.twig', [
            'name' => 'Thibaud', // Pass data to the view
        ]);
    }

    #[Route('/register', name: 'auth.register')]
    public function register(): Response
    {
        // Render the 'hello.html.twig' template
        return $this->render('auth/register.html.twig', [
            'name' => 'Thibaud', // Pass data to the view
        ]);
    }
}

templates/auth.html.twig
<!DOCTYPE html>
<html class="h-full" data-theme="true" data-theme-mode="light" dir="ltr" lang="en">
<head>
    <base href="../../">
    <title>Metronic - Tailwind CSS</title>
    <meta charset="utf-8"/>
    <meta content="follow, index" name="robots"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <link href="{{ asset('media/icon.png') }}" rel="shortcut icon"/>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <link href="{{ asset('metronic/vendors/apexcharts/apexcharts.css') }}" rel="stylesheet"/>
    <link href="{{ asset('metronic/vendors/keenicons/styles.bundle.css') }}" rel="stylesheet"/>
    <link href="{{ asset('metronic/css/styles.css') }}" rel="stylesheet"/>
</head>
<body class="antialiased flex h-full text-base text-gray-700 [--tw-page-bg:#F6F6F9] [--tw-page-bg-dark:var(--tw-coal-200)]
        [--tw-content-bg:var(--tw-light)] [--tw-content-bg-dark:var(--tw-coal-500)] [--tw-content-scrollbar-color:#e8e8e8]
        [--tw-header-height:60px] [--tw-sidebar-width:90px] bg-[--tw-page-bg] dark:bg-[--tw-page-bg-dark]">
<!-- Theme Mode -->
<script>
        const defaultThemeMode = 'light'; // light|dark|system
        let themeMode;
        if ( document.documentElement ) {
                if ( localStorage.getItem('theme') ) {
                        themeMode = localStorage.getItem('theme');
                } else if ( document.documentElement.hasAttribute('data-theme-mode') ) {
                        themeMode = document.documentElement.getAttribute('data-theme-mode');
                } else {themeMode = defaultThemeMode;}

                if ( themeMode === 'system' ) {themeMode = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';}
                document.documentElement.classList.add(themeMode);
        }
</script>
<!-- End of Theme Mode -->

<!-- Page -->
<style>
    .page-bg {
        background-image: url({{ asset('metronic/media/images/2600x1200/bg-10.png')}});
    }
    .dark .page-bg {
        background-image: url({{ asset('metronic/media/images/2600x1200/bg-10-dark.png')}});
    }
</style>

{% block body %}{% endblock %}
<!-- End of Page -->

<!-- Scripts -->
<script src="{{ asset('metronic/js/core.bundle.js') }}"></script>
<script src="{{ asset('metronic/vendors/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ asset('metronic/js/widgets/general.js') }}"></script>
<!-- End of Scripts -->
</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html class="h-full" data-theme="true" data-theme-mode="light" dir="ltr" lang="fr">
<head>
    <title>BookMaster</title>
    <meta charset="utf-8"/>
    <meta content="follow, index" name="robots"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <link href="{{ asset('media/icon.png') }}" rel="shortcut icon"/>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <link href="{{ asset('metronic/vendors/apexcharts/apexcharts.css') }}" rel="stylesheet"/>
    <link href="{{ asset('metronic/vendors/keenicons/styles.bundle.css') }}" rel="stylesheet"/>
    <link href="{{ asset('metronic/css/styles.css') }}" rel="stylesheet"/>
</head>
<body class="antialiased flex h-full text-base text-gray-700 [--tw-page-bg:#F6F6F9] [--tw-page-bg-dark:var(--tw-coal-200)]
        [--tw-content-bg:var(--tw-light)] [--tw-content-bg-dark:var(--tw-coal-500)] [--tw-content-scrollbar-color:#e8e8e8]
        [--tw-header-height:60px] [--tw-sidebar-width:90px] bg-[--tw-page-bg] dark:bg-[--tw-page-bg-dark]">
    <!-- Theme Mode -->
    <script>
            const defaultThemeMode = 'light'; // light|dark|system
            let themeMode;
            if ( document.documentElement ) {
                if ( localStorage.getItem('theme') ) {
                    themeMode = localStorage.getItem('theme');
                } else if ( document.documentElement.hasAttribute('data-theme-mode') ) {
                    themeMode = document.documentElement.getAttribute('data-theme-mode');
                } else {themeMode = defaultThemeMode;}

                if ( themeMode === 'system' ) {themeMode = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';}
                document.documentElement.classList.add(themeMode);
            }
    </script>
    <!-- End of Theme Mode -->

    <!-- Page -->
    <!-- Base -->
    <div class="flex grow">
        <!-- Header -->
        {% include 'components/main/header.html.twig' %}
        <!-- End of Header -->

        <!-- Wrapper -->
        <div class="flex flex-col lg:flex-row grow pt-[--tw-header-height] lg:pt-0">
            <!-- Sidebar -->
            {% include 'components/main/sidebar.html.twig' %}
            <!-- End of Sidebar -->

            <!-- Main -->
            <div class="flex flex-col grow rounded-xl bg-[--tw-content-bg] dark:bg-[--tw-content-bg-dark] border border-gray-300 dark:border-gray-200 lg:ms-[--tw-sidebar-width] mt-0 lg:mt-5 m-5">
                <div class="flex flex-col grow lg:scrollable-y-auto lg:[scrollbar-width:auto] lg:light:[--tw-scrollbar-thumb-color:var(--tw-content-scrollbar-color)] pt-5"
                     id="scrollable_content">
                    <main class="grow" role="content">
                        <!-- Toolbar -->
                        {% include 'components/main/toolbar.html.twig' %}
                        <!-- End of Toolbar -->
                        <!-- Container -->
                        <div class="container-fixed">
                            {% block body %}{% endblock %}
                        </div>
                        <!-- End of Container -->
                    </main>
                </div>
                <!-- Footer -->
                {% include 'components/main/footer.html.twig' %}
                <!-- End of Footer -->
            </div>
            <!-- End of Main -->
        </div>
        <!-- End of Wrapper -->
    </div>
    <!-- End of Base -->
    {% include 'modals/search.html.twig' %}
    {% include 'modals/book.html.twig' %}
    <!-- End of Page -->

    <!-- Scripts -->
    <script src="{{ asset('metronic/js/core.bundle.js') }}"></script>
    <script src="{{ asset('metronic/vendors/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ asset('metronic/js/widgets/general.js') }}"></script>
    <!-- End of Scripts -->
</body>
</html>

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Catégorie</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Note</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <div class="flex flex-col gap-2">
                                <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                   href="#">
                                    Le Moine qui vendit sa Ferrari
                                </a>
                                <span class="text-2sm text-gray-700 font-normal leading-3">
                                    Un conte sur la quête du bonheur et du succès intérieur.
                                </span>
                            </div>
                        </td>
                        <td>Spiritualité</td>
                        <td>
                            <div class="rating">
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16"
                            data-datatable-size="true" name="perpage">
                    </select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures en cours
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#current-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table  class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                            <span class="sort">
                                <span class="sort-label">Modifié le</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksRead %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#">
                                        ERREUR : Impossible de récupérer le titre
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                    ERREUR : Impossible de récupérer la description
                                </span>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookRead.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/radarChart.html.twig
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">
            Répartition de mes lectures
        </h3>
    </div>
    <div class="card-body flex flex-col gap-5">
        <figure>
            <img src="{{  asset('media/charts/Radar_Sample.png') }}" alt="Radar Sample"/>
        </figure>
    </div>
</div>

templates/components/main/footer.html.twig
<footer class="footer">
    <!-- Container -->
    <div class="container-fixed">
        <div class="flex flex-col md:flex-row justify-center md:justify-between items-center gap-3 py-5">
            <div class="flex order-2 md:order-1 gap-2 font-normal text-2sm">
                <span class="text-gray-500">2024©</span>
                <a class="text-gray-600 hover:text-primary" href="#">
                    BookMaster
                </a>
            </div>
            <nav class="flex order-1 md:order-2 gap-4 font-normal text-2sm text-gray-600">
                <a class="hover:text-primary" href="#">FAQ</a>
                <a class="hover:text-primary" href="#">Support</a>
            </nav>
        </div>
    </div>
    <!-- End of Container -->
</footer>

templates/components/main/header.html.twig
<header class="flex lg:hidden items-center fixed z-10 top-0 start-0 end-0 shrink-0 bg-[--tw-page-bg] dark:bg-[--tw-page-bg-dark] h-[--tw-header-height]"
        id="header">
    <!-- Container -->
    <div class="container-fixed flex items-center justify-between flex-wrap gap-3">
        <a href="/">
            <img class="dark:hidden" style="max-width: 30px;" src="{{ asset('media/icon.png') }}"/>
            <img class="hidden dark:block" style="max-width: 30px;" src="{{ asset('media/icon-dark.png') }}"/>
        </a>
        <button class="btn btn-icon btn-light btn-clear btn-sm -me-1" data-drawer-toggle="#sidebar">
            <i class="ki-filled ki-menu">
            </i>
        </button>
    </div>
    <!-- End of Container -->
</header>

templates/components/main/toolbar.html.twig
<div class="pb-5">
    <!-- Container -->
    <div class="container-fixed flex items-center justify-between flex-wrap gap-3">
        <div class="flex items-center flex-wrap gap-1 lg:gap-5">
            <h1 class="font-medium text-base text-gray-900"></h1>
            <div class="flex items-center flex-wrap gap-1 text-sm">
                <a class="text-gray-700 hover:text-primary" href="#">
                    Accueil
                </a>
            </div>
        </div>
        <div class="flex items-center flex-wrap gap-1.5 lg:gap-2.5">
            <button class="btn btn-icon btn-icon-lg size-8 rounded-md hover:bg-gray-200 dropdown-open:bg-gray-200 hover:text-primary text-gray-600"
                    data-modal-toggle="#search_modal">
                <i class="ki-filled ki-magnifier !text-base">
                </i>
            </button>
        </div>
    </div>
    <!-- End of Container -->
</div>

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FrontController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/wamp64/www/EC_CODE/src/Controller/FrontController.php</code></li>
        <li>Your template at <code>C:/wamp64/www/EC_CODE/templates/front/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/modals/book.html.twig
<div class="modal" data-modal="true" id="book_modal">
    <div class="modal-content max-w-[600px] top-[15%]">
        <div class="modal-header py-4 px-5">
            <h3 class="modal-title">Ma lecture</h3>
        </div>
        <div class="modal-body p-0 pb-5">
            <div class="scrollable-y-auto" data-scrollable="true" data-scrollable-max-height="auto"
                 data-scrollable-offset="300px">
                <form>
                    <div class="flex flex-col gap-5 p-5">
                        <div class="flex flex-col gap-1">
                            <label for="book" class="form-label font-normal text-gray-900">Livre</label>
                            <select id="book" class="select">
                                <option>Livre 1</option>
                                <option>Livre 2</option>
                            </select>
                        </div>

                        <div class="flex flex-col gap-1">
                            <label class="form-label font-normal text-gray-900">Mes notes</label>
                            <div class="flex flex-col w-full gap-1">
                            <textarea name="description" class="textarea"
                                      placeholder="Notez-ici les idées importantes de l'oeuvre."></textarea>
                            </div>
                        </div>

                        <div class="flex flex-col gap-1">
                            <label for="book" class="form-label font-normal text-gray-900">Note</label>
                            <select id="book" class="select" name="rating">
                                <option>1</option>
                                <option>1.5</option>
                                <option>2</option>
                                <option>2.5</option>
                                <option>3</option>
                                <option>3.5</option>
                                <option>4</option>
                                <option>4.5</option>
                                <option>5</option>
                            </select>
                        </div>

                        <div class="flex flex-col gap-1">
                            <label class="switch">
                                <span class="switch-label font-normal text-gray-900">Lecture terminée</span>
                                <input name="check" type="checkbox" value="0"/>
                            </label>
                        </div>

                        <div class="flex">
                            <button type="submit" class="btn btn-primary">Enregistrer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>